title: OpenfishOS
author: Titenko Maksym
email: titenko.m@gmail.com
description: >
  OpenfishOS is an elegant, beautiful and easy-to-use Linux desktop operating system. It runs Cutefish Desktop based on Ubuntu and has a modern style design. Our goal is to provide users with a comfortable interface design, better user experience and a better choice.

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- github.md

footer_icons:
- username: OpenfishOS
  url: https://github.com/OpenfishOS
  icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
